version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ipds_db
    restart: always
    environment:
      POSTGRES_DB: ipds_db
      POSTGRES_USER: ipds_user
      POSTGRES_PASSWORD: ipds123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
      build: .
      container_name: ipds_web
      restart: always
      depends_on:
        - db
      env_file:
        - .env
      ports:
        - "5000:5000"
      volumes:
        - ./data:/app/data

volumes:
  postgres_data: