"""baseline_ipds

Revision ID: fe94a4f469db
Revises: 
Create Date: 2026-02-03 22:47:12.712143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe94a4f469db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.CheckConstraint("status IN ('open','closed','cancelled')", name='jobs_status_chk'),
    sa.PrimaryKeyConstraint('job_id'),
    schema='ipds'
    )
    op.create_table('operators',
    sa.Column('operator_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('operator_id'),
    schema='ipds'
    )
    op.create_table('import_session',
    sa.Column('import_session_id', sa.BigInteger(), nullable=False),
    sa.Column('operator_id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('uut_serial', sa.Text(), nullable=False),
    sa.Column('session_purpose', sa.Text(), server_default='initial', nullable=False),
    sa.CheckConstraint("session_purpose IN ('initial','retake','rework','other')", name='import_session_purpose_chk'),
    sa.CheckConstraint("status IN ('running','completed','failed')", name='import_session_status_chk'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='import_session_time_chk'),
    sa.ForeignKeyConstraint(['job_id'], ['ipds.jobs.job_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['ipds.operators.operator_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('import_session_id'),
    schema='ipds'
    )
    op.create_index('idx_import_session_job_id', 'import_session', ['job_id'], unique=False, schema='ipds')
    op.create_index('idx_import_session_operator_id', 'import_session', ['operator_id'], unique=False, schema='ipds')
    op.create_index('idx_import_session_uut_serial', 'import_session', ['uut_serial'], unique=False, schema='ipds')
    op.create_table('exports',
    sa.Column('export_id', sa.BigInteger(), nullable=False),
    sa.Column('import_session_id', sa.BigInteger(), nullable=False),
    sa.Column('export_path', sa.Text(), nullable=False),
    sa.Column('manifest_path', sa.Text(), nullable=False),
    sa.Column('manifest_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='created', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created','archived','ready','failed')", name='exports_status_chk'),
    sa.ForeignKeyConstraint(['import_session_id'], ['ipds.import_session.import_session_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('export_id'),
    schema='ipds'
    )
    op.create_index('idx_exports_import_session_id', 'exports', ['import_session_id'], unique=False, schema='ipds')
    op.create_table('media',
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('import_session_id', sa.BigInteger(), nullable=False),
    sa.Column('adapter', sa.Text(), nullable=False),
    sa.Column('vendor_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['import_session_id'], ['ipds.import_session.import_session_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('media_id'),
    sa.UniqueConstraint('adapter', 'vendor_id', name='media_dedupe_uq'),
    schema='ipds'
    )
    op.create_index('idx_media_import_session_id', 'media', ['import_session_id'], unique=False, schema='ipds')
    op.create_index('idx_media_imported_at', 'media', ['imported_at'], unique=False, schema='ipds')
    op.create_table('decisions',
    sa.Column('decision_id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('accepted','rejected')", name='decisions_status_chk'),
    sa.ForeignKeyConstraint(['media_id'], ['ipds.media.media_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('media_id', name='decisions_one_per_media_uq'),
    schema='ipds'
    )
    op.create_table('export_deliveries',
    sa.Column('delivery_id', sa.BigInteger(), nullable=False),
    sa.Column('export_id', sa.BigInteger(), nullable=False),
    sa.Column('delivered_by', sa.Text(), nullable=False),
    sa.Column('destination_path', sa.Text(), nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("result IN ('succeeded','failed')", name='export_deliveries_result_chk'),
    sa.ForeignKeyConstraint(['delivered_by'], ['ipds.operators.operator_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['export_id'], ['ipds.exports.export_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('delivery_id'),
    schema='ipds'
    )
    op.create_index('idx_export_deliveries_delivered_at', 'export_deliveries', ['delivered_at'], unique=False, schema='ipds')
    op.create_index('idx_export_deliveries_delivered_by', 'export_deliveries', ['delivered_by'], unique=False, schema='ipds')
    op.create_index('idx_export_deliveries_export_id', 'export_deliveries', ['export_id'], unique=False, schema='ipds')
    op.create_table('local_archives',
    sa.Column('archive_id', sa.BigInteger(), nullable=False),
    sa.Column('export_id', sa.BigInteger(), nullable=False),
    sa.Column('archive_path', sa.Text(), nullable=False),
    sa.Column('verify_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verify_status IN ('pending','verified','failed')", name='local_archives_verify_status_chk'),
    sa.ForeignKeyConstraint(['export_id'], ['ipds.exports.export_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('archive_id'),
    sa.UniqueConstraint('export_id', name='local_archives_one_per_export_uq'),
    schema='ipds'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_archives', schema='ipds')
    op.drop_index('idx_export_deliveries_export_id', table_name='export_deliveries', schema='ipds')
    op.drop_index('idx_export_deliveries_delivered_by', table_name='export_deliveries', schema='ipds')
    op.drop_index('idx_export_deliveries_delivered_at', table_name='export_deliveries', schema='ipds')
    op.drop_table('export_deliveries', schema='ipds')
    op.drop_table('decisions', schema='ipds')
    op.drop_index('idx_media_imported_at', table_name='media', schema='ipds')
    op.drop_index('idx_media_import_session_id', table_name='media', schema='ipds')
    op.drop_table('media', schema='ipds')
    op.drop_index('idx_exports_import_session_id', table_name='exports', schema='ipds')
    op.drop_table('exports', schema='ipds')
    op.drop_index('idx_import_session_uut_serial', table_name='import_session', schema='ipds')
    op.drop_index('idx_import_session_operator_id', table_name='import_session', schema='ipds')
    op.drop_index('idx_import_session_job_id', table_name='import_session', schema='ipds')
    op.drop_table('import_session', schema='ipds')
    op.drop_table('operators', schema='ipds')
    op.drop_table('jobs', schema='ipds')
    # ### end Alembic commands ###
